# phase2_seed.py — sample content for the "Scam ya Safe?" game and the tests.
# 20 game items + 10 test questions, each fully localized (en/hi/mr/gu).
# L() is a tiny helper so the localized dicts stay short and readable.


def L(en, hi, mr, gu):
    return {"en": en, "hi": hi, "mr": mr, "gu": gu}


# --- 20 game items (type, level, category, is_scam, sender, body, explanation) ---
SEED_GAME_ITEMS = [
    # BRONZE (easy) --------------------------------------------------------
    {"order": 1, "type": "sms", "level": "bronze", "category": "phishing", "is_scam": True, "sender": "VM-KYCUPD",
     "body": L("Your bank account will be blocked today. Update KYC now: http://bit.ly/kyc-fix",
               "आपका बैंक खाता आज बंद हो जाएगा। अभी KYC अपडेट करें: http://bit.ly/kyc-fix",
               "तुमचे बँक खाते आज बंद होईल. आत्ता KYC अपडेट करा: http://bit.ly/kyc-fix",
               "તમારું બેંક ખાતું આજે બંધ થશે. હમણાં KYC અપડેટ કરો: http://bit.ly/kyc-fix"),
     "explanation": L("Banks never send KYC links by SMS. The short link is a trap.",
                       "बैंक SMS पर KYC लिंक नहीं भेजते। छोटा लिंक जाल है।",
                       "बँक SMS वर KYC लिंक पाठवत नाहीत. छोटी लिंक सापळा आहे.",
                       "બેંક SMS પર KYC લિંક મોકલતી નથી. ટૂંકી લિંક જાળ છે.")},
    {"order": 2, "type": "sms", "level": "bronze", "category": "phishing", "is_scam": False, "sender": "AX-HDFCBK",
     "body": L("Rs 2,000 debited from a/c XX34 on 12-Jun. Not you? Call 18002586161.",
               "12-जून को खाते XX34 से Rs 2,000 कटे। आपने नहीं किया? कॉल 18002586161।",
               "12-जून रोजी खाते XX34 मधून Rs 2,000 कापले. तुम्ही नाही? कॉल 18002586161.",
               "12-જૂને ખાતા XX34 માંથી Rs 2,000 કપાયા. તમે નહીં? કૉલ 18002586161."),
     "explanation": L("A normal bank alert. No link, no OTP asked. This is safe.",
                       "सामान्य बैंक अलर्ट। कोई लिंक या OTP नहीं। यह सुरक्षित है।",
                       "सामान्य बँक अलर्ट. लिंक किंवा OTP नाही. हे सुरक्षित आहे.",
                       "સામાન્ય બેંક એલર્ટ. લિંક કે OTP નથી. આ સુરક્ષિત છે.")},
    {"order": 3, "type": "whatsapp", "level": "bronze", "category": "phishing", "is_scam": True, "sender": "+91 90000 11111",
     "body": L("Congratulations! You won a Rs 25 lakh KBC lottery. Send your bank details to claim.",
               "बधाई हो! आपने KBC 25 लाख की लॉटरी जीती। बैंक जानकारी भेजें।",
               "अभिनंदन! तुम्ही KBC 25 लाख लॉटरी जिंकली. बँक माहिती पाठवा.",
               "અભિનંદન! તમે KBC 25 લાખ લોટરી જીત્યા. બેંક વિગત મોકલો."),
     "explanation": L("KBC never gives lottery on WhatsApp. Never share bank details.",
                       "KBC WhatsApp पर लॉटरी नहीं देता। बैंक जानकारी न दें।",
                       "KBC WhatsApp वर लॉटरी देत नाही. बँक माहिती देऊ नका.",
                       "KBC WhatsApp પર લોટરી આપતું નથી. બેંક વિગત ન આપો.")},
    {"order": 4, "type": "call", "level": "bronze", "category": "phishing", "is_scam": True, "sender": "+91 88888 22222",
     "body": L("I am calling from your bank. Tell me the OTP you just received to stop fraud.",
               "मैं आपके बैंक से बोल रहा हूँ। ठगी रोकने के लिए अभी आया OTP बताएँ।",
               "मी तुमच्या बँकेतून बोलतोय. फसवणूक थांबवण्यासाठी आलेला OTP सांगा.",
               "હું તમારી બેંકમાંથી બોલું છું. છેતરરૂપિયું રોકવા આવેલો OTP કહો."),
     "explanation": L("Bank staff never ask for OTP. Cut the call.",
                       "बैंक कर्मचारी OTP नहीं माँगते। कॉल काटें।",
                       "बँक कर्मचारी OTP विचारत नाहीत. कॉल तोडा.",
                       "બેંક કર્મચારી OTP માંગતા નથી. કૉલ કાપો.")},
    # SILVER (fake UPI) ----------------------------------------------------
    {"order": 5, "type": "whatsapp", "level": "silver", "category": "upi", "is_scam": True, "sender": "+91 77777 33333",
     "body": L("I sent Rs 5,000 to you by mistake. Please accept the request and return it.",
               "मैंने गलती से Rs 5,000 भेज दिए। रिक्वेस्ट स्वीकार कर वापस कर दें।",
               "मी चुकून Rs 5,000 पाठवले. विनंती स्वीकारून परत करा.",
               "મેં ભૂલથી Rs 5,000 મોકલ્યા. રિક્વેસ્ટ સ્વીકારી પરત કરો."),
     "explanation": L("Accepting a UPI request SENDS money, not receives. It is a trick.",
                       "UPI रिक्वेस्ट स्वीकारने से पैसे जाते हैं, आते नहीं। यह चाल है।",
                       "UPI विनंती स्वीकारल्याने पैसे जातात, येत नाहीत. ही चाल आहे.",
                       "UPI રિક્વેસ્ટ સ્વીકારવાથી પૈસા જાય છે, આવતા નથી. આ યુક્તિ છે.")},
    {"order": 6, "type": "sms", "level": "silver", "category": "upi", "is_scam": False, "sender": "AD-GPAY",
     "body": L("You received Rs 500 from Suresh via UPI. Balance updated.",
               "आपको Suresh से UPI द्वारा Rs 500 मिले। बैलेंस अपडेट हुआ।",
               "तुम्हाला Suresh कडून UPI ने Rs 500 मिळाले. बॅलन्स अपडेट.",
               "તમને Suresh પાસેથી UPI દ્વારા Rs 500 મળ્યા. બેલેન્સ અપડેટ."),
     "explanation": L("A real 'money received' message needs no action. Safe.",
                       "असली 'पैसे मिले' मैसेज में कुछ नहीं करना। सुरक्षित।",
                       "खरा 'पैसे मिळाले' मेसेज, काही करायचे नाही. सुरक्षित.",
                       "સાચો 'પૈસા મળ્યા' મેસેજ, કંઈ કરવાનું નથી. સુરક્ષિત.")},
    {"order": 7, "type": "call", "level": "silver", "category": "upi", "is_scam": True, "sender": "+91 99999 44444",
     "body": L("To get your gas subsidy, open GPay and enter your UPI PIN on my request.",
               "गैस सब्सिडी पाने के लिए GPay खोलें और मेरी रिक्वेस्ट पर UPI PIN डालें।",
               "गॅस सबसिडीसाठी GPay उघडा आणि माझ्या विनंतीवर UPI PIN टाका.",
               "ગેસ સબસિડી માટે GPay ખોલો અને મારી રિક્વેસ્ટ પર UPI PIN નાખો."),
     "explanation": L("You never enter a UPI PIN to RECEIVE money. Scam.",
                       "पैसे लेने के लिए UPI PIN कभी नहीं डालते। ठगी।",
                       "पैसे घेण्यासाठी UPI PIN कधीच टाकत नाही. फसवणूक.",
                       "પૈસા લેવા UPI PIN ક્યારેય નાખતા નથી. છેતરરૂપિયું.")},
    {"order": 8, "type": "website", "level": "silver", "category": "upi", "is_scam": True, "sender": "www.paytm-kyc-verify.in",
     "body": L("Verify your Paytm wallet KYC. Enter mobile, UPI PIN and OTP to continue.",
               "अपना Paytm वॉलेट KYC सत्यापित करें। मोबाइल, UPI PIN और OTP डालें।",
               "तुमचे Paytm वॉलेट KYC सत्यापित करा. मोबाइल, UPI PIN आणि OTP टाका.",
               "તમારું Paytm વૉલેટ KYC ચકાસો. મોબાઇલ, UPI PIN અને OTP નાખો."),
     "explanation": L("Fake site (not paytm.com). No real site asks your UPI PIN.",
                       "नकली साइट (paytm.com नहीं)। असली साइट UPI PIN नहीं माँगती।",
                       "खोटी साइट (paytm.com नाही). खरी साइट UPI PIN विचारत नाही.",
                       "ખોટી સાઇટ (paytm.com નહીં). સાચી સાઇટ UPI PIN માંગતી નથી.")},
    # GOLD (job fraud) -----------------------------------------------------
    {"order": 9, "type": "whatsapp", "level": "gold", "category": "job", "is_scam": True, "sender": "+91 91234 56780",
     "body": L("Work from home! Like 20 YouTube videos daily, earn Rs 5,000. Pay Rs 500 to join.",
               "घर बैठे काम! रोज़ 20 वीडियो लाइक करो, Rs 5,000 कमाओ। जॉइन के लिए Rs 500 दो।",
               "घरून काम! रोज 20 व्हिडिओ लाइक करा, Rs 5,000 कमवा. जॉइनसाठी Rs 500 द्या.",
               "ઘરેથી કામ! રોજ 20 વિડિયો લાઇક કરો, Rs 5,000 કમાઓ. જોડાવા Rs 500 આપો."),
     "explanation": L("Real jobs never ask you to pay first. Task-and-earn is fraud.",
                       "असली नौकरी पहले पैसे नहीं माँगती। टास्क-कमाई ठगी है।",
                       "खरी नोकरी आधी पैसे मागत नाही. टास्क-कमाई फसवणूक आहे.",
                       "સાચી નોકરી પહેલા પૈસા માંગતી નથી. ટાસ્ક-કમાણી છેતરરૂપિયું છે.")},
    {"order": 10, "type": "sms", "level": "gold", "category": "job", "is_scam": False, "sender": "VK-NCS",
     "body": L("NCS: Your job application at ABC Ltd is received. Interview date will be shared.",
               "NCS: ABC Ltd में आपका आवेदन मिला। इंटरव्यू की तारीख बताई जाएगी।",
               "NCS: ABC Ltd मध्ये तुमचा अर्ज मिळाला. मुलाखतीची तारीख कळवली जाईल.",
               "NCS: ABC Ltd માં તમારી અરજી મળી. ઇન્ટરવ્યૂ તારીખ જણાવાશે."),
     "explanation": L("A normal application update. No money or link asked. Safe.",
                       "सामान्य आवेदन अपडेट। पैसे या लिंक नहीं। सुरक्षित।",
                       "सामान्य अर्ज अपडेट. पैसे किंवा लिंक नाही. सुरक्षित.",
                       "સામાન્ય અરજી અપડેટ. પૈસા કે લિંક નથી. સુરક્ષિત.")},
    {"order": 11, "type": "call", "level": "gold", "category": "job", "is_scam": True, "sender": "+91 90909 09090",
     "body": L("Amazon HR here. Pay Rs 1,999 registration and get a work-from-home job today.",
               "Amazon HR बोल रहे हैं। Rs 1,999 रजिस्ट्रेशन दो, आज घर से नौकरी पाओ।",
               "Amazon HR बोलतोय. Rs 1,999 नोंदणी द्या, आज घरून नोकरी मिळवा.",
               "Amazon HR બોલે છે. Rs 1,999 રજીસ્ટ્રેશન આપો, આજે ઘરેથી નોકરી મેળવો."),
     "explanation": L("Big companies never charge a registration fee. Scam.",
                       "बड़ी कंपनियाँ रजिस्ट्रेशन फीस नहीं लेतीं। ठगी।",
                       "मोठ्या कंपन्या नोंदणी फी घेत नाहीत. फसवणूक.",
                       "મોટી કંપનીઓ રજીસ્ટ્રેશન ફી લેતી નથી. છેતરરૂપિયું.")},
    {"order": 12, "type": "website", "level": "gold", "category": "job", "is_scam": True, "sender": "www.govt-jobs-apply.xyz",
     "body": L("Guaranteed government job! Pay Rs 3,000 processing fee, no exam needed.",
               "पक्की सरकारी नौकरी! Rs 3,000 फीस दो, कोई परीक्षा नहीं।",
               "हमखास सरकारी नोकरी! Rs 3,000 फी द्या, परीक्षा नाही.",
               "ખાતરીપૂર્વક સરકારી નોકરી! Rs 3,000 ફી આપો, પરીક્ષા નહીં."),
     "explanation": L("Govt jobs need exams, never a fee to a .xyz site. Scam.",
                       "सरकारी नौकरी परीक्षा से मिलती है, .xyz साइट को फीस नहीं। ठगी।",
                       "सरकारी नोकरी परीक्षेने मिळते, .xyz साइटला फी नाही. फसवणूक.",
                       "સરકારી નોકરી પરીક્ષાથી મળે, .xyz સાઇટને ફી નહીં. છેતરરૂપિયું.")},
    # PLATINUM (trading fraud) --------------------------------------------
    {"order": 13, "type": "whatsapp", "level": "platinum", "category": "trading", "is_scam": True, "sender": "Stock Guru Ma'am",
     "body": L("Join my VIP group. Invest Rs 10,000, get Rs 40,000 in 7 days. 100% guaranteed profit.",
               "मेरे VIP ग्रुप में आओ। Rs 10,000 लगाओ, 7 दिन में Rs 40,000 पाओ। 100% पक्का मुनाफा।",
               "माझ्या VIP ग्रुपमध्ये या. Rs 10,000 गुंतवा, 7 दिवसांत Rs 40,000. 100% नफा.",
               "મારા VIP ગ્રુપમાં આવો. Rs 10,000 રોકો, 7 દિવસમાં Rs 40,000. 100% નફો."),
     "explanation": L("No one guarantees 4x in a week. Trading tip groups are fraud.",
                       "एक हफ्ते में 4 गुना कोई नहीं देता। ट्रेडिंग टिप ग्रुप ठगी हैं।",
                       "आठवड्यात 4 पट कोणी देत नाही. ट्रेडिंग टिप ग्रुप फसवणूक.",
                       "અઠવાડિયામાં 4 ગણું કોઈ આપતું નથી. ટ્રેડિંગ ટિપ ગ્રુપ છેતરરૂપિયું.")},
    {"order": 14, "type": "sms", "level": "platinum", "category": "trading", "is_scam": True, "sender": "TX-PROFIT",
     "body": L("Your trading account earned Rs 88,000. Pay 10% tax now to withdraw: http://pay-now.link",
               "आपके ट्रेडिंग खाते ने Rs 88,000 कमाए। निकालने को 10% टैक्स दें: http://pay-now.link",
               "तुमच्या ट्रेडिंग खात्याने Rs 88,000 कमावले. काढण्यासाठी 10% कर द्या: http://pay-now.link",
               "તમારા ટ્રેડિંગ ખાતાએ Rs 88,000 કમાયા. ઉપાડવા 10% ટેક્સ આપો: http://pay-now.link"),
     "explanation": L("Asking a fee to release your 'profit' is a classic scam.",
                       "'मुनाफा' देने से पहले फीस माँगना पक्की ठगी है।",
                       "'नफा' देण्याआधी फी मागणे ही ठरलेली फसवणूक.",
                       "'નફો' આપતા પહેલા ફી માંગવી એ ચોક્કસ છેતરરૂપિયું.")},
    {"order": 15, "type": "website", "level": "platinum", "category": "trading", "is_scam": False, "sender": "www.nseindia.com",
     "body": L("NSE India: Market closes at 3:30 PM. Always invest through a SEBI-registered broker.",
               "NSE India: बाज़ार 3:30 बजे बंद। हमेशा SEBI पंजीकृत ब्रोकर से निवेश करें।",
               "NSE India: बाजार 3:30 वाजता बंद. नेहमी SEBI नोंदणीकृत ब्रोकरकडून गुंतवा.",
               "NSE India: બજાર 3:30 વાગ્યે બંધ. હંમેશાં SEBI નોંધાયેલ બ્રોકરથી રોકાણ કરો."),
     "explanation": L("Official NSE site with general advice. No trap. Safe.",
                       "आधिकारिक NSE साइट, सामान्य सलाह। कोई जाल नहीं। सुरक्षित।",
                       "अधिकृत NSE साइट, सामान्य सल्ला. जाल नाही. सुरक्षित.",
                       "અધિકૃત NSE સાઇટ, સામાન્ય સલાહ. જાળ નથી. સુરક્ષિત.")},
    {"order": 16, "type": "call", "level": "platinum", "category": "trading", "is_scam": True, "sender": "+91 80000 10000",
     "body": L("Download this app and I will trade for you. Just give me remote access and your login.",
               "यह ऐप डाउनलोड करो, मैं आपके लिए ट्रेड करूँगा। रिमोट एक्सेस और लॉगिन दे दो।",
               "हे ॲप डाउनलोड करा, मी तुमच्यासाठी ट्रेड करेन. रिमोट अ‍ॅक्सेस आणि लॉगिन द्या.",
               "આ એપ ડાઉનલોડ કરો, હું તમારા માટે ટ્રેડ કરીશ. રિમોટ એક્સેસ અને લોગિન આપો."),
     "explanation": L("Never give remote access or login. They will empty your account.",
                       "रिमोट एक्सेस या लॉगिन कभी न दें। वे खाता खाली कर देंगे।",
                       "रिमोट अ‍ॅक्सेस किंवा लॉगिन देऊ नका. ते खाते रिकामे करतील.",
                       "રિમોટ એક્સેસ કે લોગિન ન આપો. તેઓ ખાતું ખાલી કરશે.")},
    # DIAMOND (loan apps) --------------------------------------------------
    {"order": 17, "type": "sms", "level": "diamond", "category": "loan", "is_scam": True, "sender": "VM-QUIKLN",
     "body": L("Instant Rs 50,000 loan, no documents! Install QuickLoan app and allow all permissions.",
               "तुरंत Rs 50,000 लोन, कोई कागज़ नहीं! QuickLoan ऐप इंस्टॉल कर सारी अनुमति दें।",
               "त्वरित Rs 50,000 कर्ज, कागद नाही! QuickLoan ॲप इन्स्टॉल करून सर्व परवानग्या द्या.",
               "તરત Rs 50,000 લોન, દસ્તાવેજ નહીં! QuickLoan એપ ઇન્સ્ટોલ કરી બધી પરમિશન આપો."),
     "explanation": L("Loan apps that want all permissions blackmail you later. Avoid.",
                       "सारी अनुमति माँगने वाले लोन ऐप बाद में ब्लैकमेल करते हैं। बचें।",
                       "सर्व परवानग्या मागणारे लोन ॲप नंतर ब्लॅकमेल करतात. टाळा.",
                       "બધી પરમિશન માંગતા લોન એપ પછી બ્લેકમેલ કરે છે. ટાળો.")},
    {"order": 18, "type": "call", "level": "diamond", "category": "loan", "is_scam": True, "sender": "+91 70000 50000",
     "body": L("Your loan is approved. Pay Rs 2,500 file charge to this UPI and money comes in 1 hour.",
               "आपका लोन मंज़ूर। इस UPI पर Rs 2,500 फाइल चार्ज दो, 1 घंटे में पैसे आएँगे।",
               "तुमचे कर्ज मंजूर. या UPI वर Rs 2,500 फाइल चार्ज द्या, 1 तासात पैसे येतील.",
               "તમારી લોન મંજૂર. આ UPI પર Rs 2,500 ફાઇલ ચાર્જ આપો, 1 કલાકમાં પૈસા આવશે."),
     "explanation": L("Real lenders cut charges from the loan, not before. Scam.",
                       "असली लोन में चार्ज लोन से कटता है, पहले नहीं। ठगी।",
                       "खऱ्या कर्जात चार्ज कर्जातून कापला जातो, आधी नाही. फसवणूक.",
                       "સાચી લોનમાં ચાર્જ લોનમાંથી કપાય, પહેલા નહીં. છેતરરૂપિયું.")},
    {"order": 19, "type": "whatsapp", "level": "diamond", "category": "loan", "is_scam": False, "sender": "+91 90040 10040",
     "body": L("Reminder: Your loan EMI of Rs 3,200 is due on 5-Jul. Pay via the bank app or branch.",
               "याद दिलाना: Rs 3,200 की EMI 5-जुलाई को देय। बैंक ऐप या शाखा से भरें।",
               "स्मरण: Rs 3,200 EMI 5-जुलैला देय. बँक ॲप किंवा शाखेतून भरा.",
               "યાદ: Rs 3,200 EMI 5-જુલાઈએ બાકી. બેંક એપ કે શાખાથી ભરો."),
     "explanation": L("A normal EMI reminder pointing to official channels. Safe.",
                       "सामान्य EMI रिमाइंडर, आधिकारिक तरीका। सुरक्षित।",
                       "सामान्य EMI स्मरण, अधिकृत मार्ग. सुरक्षित.",
                       "સામાન્ય EMI રિમાઇન્ડર, અધિકૃત માર્ગ. સુરક્ષિત.")},
    {"order": 20, "type": "website", "level": "diamond", "category": "loan", "is_scam": True, "sender": "www.rbi-loan-approve.co",
     "body": L("RBI has approved your loan. Enter Aadhaar, PAN and OTP to release Rs 1,00,000.",
               "RBI ने आपका लोन मंज़ूर किया। Rs 1,00,000 पाने को आधार, PAN और OTP डालें।",
               "RBI ने तुमचे कर्ज मंजूर केले. Rs 1,00,000 साठी आधार, PAN आणि OTP टाका.",
               "RBI એ તમારી લોન મંજૂર કરી. Rs 1,00,000 માટે આધાર, PAN અને OTP નાખો."),
     "explanation": L("RBI never gives loans to people. Fake site stealing your ID.",
                       "RBI लोगों को लोन नहीं देता। नकली साइट आपकी ID चुरा रही है।",
                       "RBI लोकांना कर्ज देत नाही. खोटी साइट तुमची ID चोरत आहे.",
                       "RBI લોકોને લોન આપતું નથી. ખોટી સાઇટ તમારી ID ચોરે છે.")},
]


def Q(order, level, category, q, opts, correct, exp):
    return {
        "order": order, "level": level, "category": category,
        "question": q, "options": opts, "correct_index": correct, "explanation": exp,
    }


# --- 10 test questions ---
SEED_TEST_QUESTIONS = [
    Q(1, "bronze", "phishing",
      L("A caller says he is from your bank and asks for the OTP. What should you do?",
        "एक कॉलर कहता है वह बैंक से है और OTP माँगता है। क्या करें?",
        "एक कॉलर म्हणतो तो बँकेतून आहे आणि OTP मागतो. काय करावे?",
        "એક કૉલર કહે તે બેંકમાંથી છે અને OTP માંગે. શું કરવું?"),
      [L("Tell the OTP", "OTP बता दें", "OTP सांगा", "OTP કહી દો"),
       L("Cut the call, never share OTP", "कॉल काटें, OTP न दें", "कॉल तोडा, OTP देऊ नका", "કૉલ કાપો, OTP ન આપો"),
       L("Send it on WhatsApp", "WhatsApp पर भेज दें", "WhatsApp वर पाठवा", "WhatsApp પર મોકલો")],
      1,
      L("Banks never ask OTP. Cutting the call is safest.",
        "बैंक OTP नहीं माँगते। कॉल काटना सुरक्षित है।",
        "बँक OTP विचारत नाहीत. कॉल तोडणे सुरक्षित.",
        "બેંક OTP માંગતી નથી. કૉલ કાપવો સુરક્ષિત.")),
    Q(2, "bronze", "phishing",
      L("A message says 'you won a lottery, pay fee to claim'. This is:",
        "मैसेज कहता है 'लॉटरी जीती, फीस दो'। यह है:",
        "मेसेज म्हणतो 'लॉटरी जिंकली, फी द्या'. हे आहे:",
        "મેસેજ કહે 'લોટરી જીત્યા, ફી આપો'. આ છે:"),
      [L("A real prize", "असली इनाम", "खरे बक्षीस", "સાચું ઇનામ"),
       L("A scam", "एक ठगी", "एक फसवणूक", "એક છેતરરૂપિયું"),
       L("A bank offer", "बैंक ऑफर", "बँक ऑफर", "બેંક ઓફર")],
      1,
      L("Winners never pay a fee first. It is a scam.",
        "जीतने वाले पहले फीस नहीं देते। ठगी है।",
        "जिंकणारे आधी फी देत नाहीत. फसवणूक आहे.",
        "જીતનારા પહેલા ફી આપતા નથી. છેતરરૂપિયું છે.")),
    Q(3, "silver", "upi",
      L("To RECEIVE money on UPI, do you need to enter your PIN?",
        "UPI पर पैसे लेने के लिए क्या PIN डालना पड़ता है?",
        "UPI वर पैसे घेण्यासाठी PIN टाकावा लागतो का?",
        "UPI પર પૈસા લેવા PIN નાખવો પડે?"),
      [L("Yes, always", "हाँ, हमेशा", "हो, नेहमी", "હા, હંમેશાં"),
       L("No, never", "नहीं, कभी नहीं", "नाही, कधीच नाही", "ના, ક્યારેય નહીં"),
       L("Only for big amounts", "बड़ी रकम के लिए", "मोठ्या रकमेसाठी", "મોટી રકમ માટે")],
      1,
      L("PIN is only for SENDING money. Receiving needs no PIN.",
        "PIN सिर्फ पैसे भेजने के लिए है। लेने में PIN नहीं।",
        "PIN फक्त पैसे पाठवण्यासाठी. घेण्यास PIN नाही.",
        "PIN ફક્ત પૈસા મોકલવા. લેવા PIN નહીં.")),
    Q(4, "silver", "upi",
      L("Someone requests money saying 'sent by mistake'. Best action?",
        "कोई 'गलती से भेजा' कहकर पैसे माँगे। सही कदम?",
        "कोणी 'चुकून पाठवले' म्हणत पैसे मागतो. योग्य कृती?",
        "કોઈ 'ભૂલથી મોકલ્યા' કહી પૈસા માંગે. યોગ્ય પગલું?"),
      [L("Approve the request", "रिक्वेस्ट स्वीकारें", "विनंती स्वीकारा", "રિક્વેસ્ટ સ્વીકારો"),
       L("Check your bank; ignore if nothing came", "बैंक देखें; कुछ न आया तो अनदेखा करें", "बँक तपासा; काही नाही तर दुर्लक्ष", "બેંક જુઓ; કંઈ ન આવ્યું તો અવગણો"),
       L("Send double back", "दोगुना लौटाएँ", "दुप्पट परत करा", "બમણું પરત કરો")],
      1,
      L("No money truly came. Approving a request would send yours.",
        "पैसे आए ही नहीं। रिक्वेस्ट से आपके पैसे चले जाएँगे।",
        "पैसे आलेच नाहीत. विनंतीने तुमचे पैसे जातील.",
        "પૈસા આવ્યા જ નથી. રિક્વેસ્ટથી તમારા પૈસા જશે.")),
    Q(5, "gold", "job",
      L("A job asks Rs 500 to join and promises daily income. It is:",
        "नौकरी जॉइन के लिए Rs 500 माँगे, रोज़ कमाई का वादा। यह है:",
        "नोकरी जॉइनसाठी Rs 500 मागते, रोज कमाईचे वचन. हे आहे:",
        "નોકરી જોડાવા Rs 500 માંગે, રોજ કમાણીનું વચન. આ છે:"),
      [L("A good chance", "अच्छा मौका", "चांगली संधी", "સારી તક"),
       L("A fraud", "एक ठगी", "एक फसवणूक", "એક છેતરરૂપિયું"),
       L("A part-time offer", "पार्ट टाइम ऑफर", "पार्ट टाइम ऑफर", "પાર્ટ ટાઇમ ઓફર")],
      1,
      L("Real jobs pay you; they do not charge to join.",
        "असली नौकरी पैसे देती है, जॉइन के पैसे नहीं लेती।",
        "खरी नोकरी पैसे देते, जॉइनचे पैसे घेत नाही.",
        "સાચી નોકરી પૈસા આપે, જોડાવાના પૈસા લેતી નથી.")),
    Q(6, "gold", "job",
      L("Which is a warning sign of a fake job?",
        "नकली नौकरी की चेतावनी कौन सी है?",
        "खोट्या नोकरीचे इशारा कोणते?",
        "ખોટી નોકરીની ચેતવણી કઈ?"),
      [L("Interview at office", "ऑफिस में इंटरव्यू", "ऑफिसमध्ये मुलाखत", "ઓફિસમાં ઇન્ટરવ્યૂ"),
       L("Asks money before joining", "जॉइन से पहले पैसे माँगे", "जॉइनआधी पैसे मागते", "જોડાતા પહેલા પૈસા માંગે"),
       L("Sends an offer letter", "ऑफर लेटर भेजे", "ऑफर लेटर पाठवते", "ઓફર લેટર મોકલે")],
      1,
      L("Paying before joining is the biggest red flag.",
        "जॉइन से पहले पैसे देना सबसे बड़ा खतरा।",
        "जॉइनआधी पैसे देणे हा मोठा धोका.",
        "જોડાતા પહેલા પૈસા આપવા સૌથી મોટું જોખમ.")),
    Q(7, "platinum", "trading",
      L("An app promises '100% guaranteed profit in 7 days'. You should:",
        "ऐप '7 दिन में 100% पक्का मुनाफा' कहे। आपको:",
        "ॲप '7 दिवसांत 100% नफा' म्हणते. तुम्ही:",
        "એપ '7 દિવસમાં 100% નફો' કહે. તમારે:"),
      [L("Invest all savings", "सारी बचत लगाएँ", "सर्व बचत गुंतवा", "બધી બચત રોકો"),
       L("Avoid it, no profit is guaranteed", "बचें, मुनाफा पक्का नहीं होता", "टाळा, नफा पक्का नसतो", "ટાળો, નફો ખાતરીપૂર્વક નથી"),
       L("Invest half", "आधा लगाएँ", "अर्धे गुंतवा", "અડધું રોકો")],
      1,
      L("Guaranteed profit does not exist. It is a trap.",
        "पक्का मुनाफा होता ही नहीं। यह जाल है।",
        "पक्का नफा असतोच नाही. हा सापळा आहे.",
        "ખાતરીપૂર્વક નફો હોતો જ નથી. આ જાળ છે.")),
    Q(8, "platinum", "trading",
      L("A 'trading mentor' wants remote access to your phone. You:",
        "'ट्रेडिंग मेंटर' फोन का रिमोट एक्सेस माँगे। आप:",
        "'ट्रेडिंग मेंटर' फोनचा रिमोट अ‍ॅक्सेस मागतो. तुम्ही:",
        "'ટ્રેડિંગ મેન્ટર' ફોનનો રિમોટ એક્સેસ માંગે. તમે:"),
      [L("Give access", "एक्सेस दें", "अ‍ॅक्सेस द्या", "એક્સેસ આપો"),
       L("Refuse completely", "पूरी तरह मना करें", "पूर्ण नकार द्या", "સંપૂર્ણ ના પાડો"),
       L("Give for 5 minutes", "5 मिनट के लिए दें", "5 मिनिटांसाठी द्या", "5 મિનિટ માટે આપો")],
      1,
      L("Remote access lets them steal everything. Never give it.",
        "रिमोट एक्सेस से वे सब चुरा सकते हैं। कभी न दें।",
        "रिमोट अ‍ॅक्सेसने ते सर्व चोरू शकतात. कधीही देऊ नका.",
        "રિમોટ એક્સેસથી બધું ચોરી શકે. ક્યારેય ન આપો.")),
    Q(9, "diamond", "loan",
      L("A loan app wants access to all your contacts and photos. This is:",
        "लोन ऐप सारे कॉन्टैक्ट और फोटो माँगे। यह है:",
        "लोन ॲप सर्व कॉन्टॅक्ट आणि फोटो मागते. हे आहे:",
        "લોન એપ બધા કોન્ટેક્ટ અને ફોટા માંગે. આ છે:"),
      [L("Normal", "सामान्य", "सामान्य", "સામાન્ય"),
       L("Dangerous, they may blackmail", "खतरनाक, ब्लैकमेल कर सकते हैं", "धोकादायक, ब्लॅकमेल करू शकतात", "ખતરનાક, બ્લેકમેલ કરી શકે"),
       L("Needed for the loan", "लोन के लिए ज़रूरी", "कर्जासाठी आवश्यक", "લોન માટે જરૂરી")],
      1,
      L("Loan apps do not need your contacts. They misuse them.",
        "लोन ऐप को कॉन्टैक्ट नहीं चाहिए। वे गलत इस्तेमाल करते हैं।",
        "लोन ॲपला कॉन्टॅक्ट नकोत. ते गैरवापर करतात.",
        "લોન એપને કોન્ટેક્ટ જોઈએ નહીં. તેઓ દુરુપયોગ કરે.")),
    Q(10, "diamond", "loan",
      L("Your loan is 'approved' but they ask a fee first via UPI. You:",
        "लोन 'मंज़ूर' है पर पहले UPI से फीस माँगे। आप:",
        "कर्ज 'मंजूर' पण आधी UPI ने फी मागतात. तुम्ही:",
        "લોન 'મંજૂર' પણ પહેલા UPI થી ફી માંગે. તમે:"),
      [L("Pay the fee", "फीस दें", "फी द्या", "ફી આપો"),
       L("Refuse; real loans deduct charges later", "मना करें; असली लोन बाद में काटता है", "नकार द्या; खरे कर्ज नंतर कापते", "ના પાડો; સાચી લોન પછી કાપે"),
       L("Pay half now", "आधी अभी दें", "अर्धी आत्ता द्या", "અડધી હમણાં આપો")],
      1,
      L("Upfront fees for an 'approved' loan are always a scam.",
        "'मंज़ूर' लोन के लिए पहले फीस हमेशा ठगी है।",
        "'मंजूर' कर्जासाठी आधी फी नेहमी फसवणूक.",
        "'મંજૂર' લોન માટે પહેલા ફી હંમેશાં છેતરરૂપિયું.")),
]
