# seed_data.py — starter content for Surakshit Digital.
# Every text field is a LocalizedText (en / hi / mr / gu). The app renders the
# user's chosen language. New languages = add a key + a new i18n file later.

from datetime import datetime, timezone

SEED_LESSONS = [
    {
        "order": 1,
        "icon": "message-text-lock",
        "category": "otp",
        "minutes": 3,
        "title": {
            "en": "Never Share Your OTP",
            "hi": "अपना OTP कभी न बताएँ",
            "mr": "तुमचा OTP कधीही सांगू नका",
            "gu": "તમારો OTP ક્યારેય શેર કરશો નહીં",
        },
        "summary": {
            "en": "Bank never asks for OTP. Sharing it can empty your account.",
            "hi": "बैंक कभी OTP नहीं पूछता। OTP बताया तो खाता खाली हो सकता है।",
            "mr": "बँक कधीच OTP विचारत नाही. OTP सांगितला तर खाते रिकामे होऊ शकते.",
            "gu": "બેંક ક્યારેય OTP પૂછતી નથી. OTP આપલો તો ખાતું ખાલી થઈ શકે.",
        },
        "steps": [
            {"text": {"en": "Banks and police never ask for OTP on calls or SMS.",
                       "hi": "बैंक या पुलिस कभी OTP नहीं पूछते।",
                       "mr": "बँक किंवा पोलीस कधीच OTP विचारत नाहीत.",
                       "gu": "બેંક કે પોલીસ ક્યારેય OTP પૂછતી નથી."}},
            {"text": {"en": "Whoever asks for OTP is a fraudster.",
                       "hi": "जो भी OTP पूछे, वह ठग है।",
                       "mr": "जो OTP विचारतो तो फसवणूक करणारा आहे.",
                       "gu": "જે OTP પૂછે તે છેતરરૂપિયો છે."}},
            {"text": {"en": "Cut the call and report on 1930.",
                       "hi": "कॉल काटें और 1930 पर बताएँ।",
                       "mr": "कॉल तोडा आणि 1930 ला कळवा.",
                       "gu": "કૉલ કાપો અને 1930 પર જણાવો."}},
        ],
        "quiz": {
            "question": {
                "en": "A 'bank officer' on call asks your OTP. What do you do?",
                "hi": "फोन पर 'बैंक अधिकारी' OTP पूछे तो क्या करें?",
                "mr": "फोनवर 'बँक अधिकारी' OTP विचारतो तर काय करावे?",
                "gu": "ફોન પર 'બેંક ઓફિસર' OTP પૂછે તો શું કરવું?",
            },
            "options": [
                {"en": "Share it quickly", "hi": "झटपट बता दें", "mr": "झटपट सांगू", "gu": "ઝટથી કહી દઉં"},
                {"en": "Cut the call and report to 1930", "hi": "कॉल काटें, 1930 पर बताएँ", "mr": "कॉल तोडा, 1930 ला कळवा", "gu": "કૉલ કાપી 1930 ને જણાવું"},
                {"en": "Give a friend's number", "hi": "दोस्त का नंबर बता दें", "mr": "मित्राचा नंबर सांगू", "gu": "મિત્રનો નંબર કહી દઉં"},
            ],
            "correct_index": 1,
        },
    },
    {
        "order": 2,
        "icon": "currency-inr",
        "category": "upi",
        "minutes": 3,
        "title": {
            "en": "Wrong UPI Request Scam",
            "hi": "गलत UPI रिक्वेस्ट ठगी",
            "mr": "चुकीची UPI विनंती फसवणूक",
            "gu": "ખોટી UPI રિક્વેસ્ટ છેતરરૂપિયું",
        },
        "summary": {
            "en": "A 'wrong payment' request can steal money when you enter PIN.",
            "hi": "'गलती से पैसे' वाली रिक्वेस्ट PIN डालते ही पैसे उड़ा देती है।",
            "mr": "'चुकीचे पैसे' विनंतीत PIN टाकताच पैसे कापले जातात.",
            "gu": "'ખોટા પૈસા' રિક્વેસ્ટમાં PIN નાખતાં પૈસા ઉડી જાય છે.",
        },
        "steps": [
            {"text": {"en": "Got a request saying 'sent by mistake'? Do not pay.",
                       "hi": "'गलती से भेजा' रिक्वेस्ट आए तो पैसे न भेजें।",
                       "mr": "'चुकीने पाठवले' विनंती आली तर पैसे पाठवू नका.",
                       "gu": "'ભૂલથી મોકલ્યા' રિક્વેસ્ટ આવે તો પૈસા ન મોકલો."}},
            {"text": {"en": "Check your bank app first. No money came? Ignore it.",
                       "hi": "पहले बैंक ऐप देखें। पैसे नहीं आए? नज़रअंदाज़ करें।",
                       "mr": "आधी बँक ॲप तपासा. पैसे आले नाहीत? दुर्लक्ष करा.",
                       "gu": "પહેલા બેંક એપ જુઓ. પૈસા ન આવ્યા? અવગણો."}},
            {"text": {"en": "Entering UPI PIN sends money. Never enter to receive.",
                       "hi": "UPI PIN डालने से पैसे जाते हैं, आते नहीं।",
                       "mr": "UPI PIN टाकल्याने पैसे जातात, येत नाहीत.",
                       "gu": "UPI PIN નાખવાથી પૈસા જાય છે, આવતા નથી."}},
        ],
        "quiz": {
            "question": {
                "en": "Someone says 'I sent ₹2,000 by mistake, please return'. What do you do?",
                "hi": "कोई कहे 'मैंने गलती से ₹2,000 भेजे, लौटा दो'। क्या करें?",
                "mr": "कोणी म्हणाले 'चुकून ₹2,000 पाठवले, परत कर'. काय करावे?",
                "gu": "કોઈ કહે 'ભૂલથી ₹2,000 મોકલ્યા, પરત કર'. શું કરવું?",
            },
            "options": [
                {"en": "Enter PIN and return it", "hi": "PIN डालकर लौटा दें", "mr": "PIN टाकून परत करू", "gu": "PIN નાખીને પરત કરું"},
                {"en": "Check bank app; if no money came, do nothing", "hi": "बैंक ऐप देखें; पैसे नहीं आए तो कुछ न करें", "mr": "बँक ॲप तपासा; पैसे नाहीत तर काही करू नका", "gu": "બેંક એપ જુઓ; પૈસા ન આવ્યા તો કંઈ ન કરો"},
                {"en": "Send money from another app", "hi": "दूसरे ऐप से भेज दें", "mr": "दुसऱ्या ॲपमधून पाठवू", "gu": "બીજી એપમાંથી મોકલી દઉં"},
            ],
            "correct_index": 1,
        },
    },
    {
        "order": 3,
        "icon": "whatsapp",
        "category": "whatsapp",
        "minutes": 2,
        "title": {
            "en": "Prize Message on WhatsApp",
            "hi": "WhatsApp पर इनाम वाला मैसेज",
            "mr": "WhatsApp वर बक्षीस मेसेज",
            "gu": "WhatsApp પર ઇનામ મેસેજ",
        },
        "summary": {
            "en": "'You won a prize' messages are fake. Do not click or forward.",
            "hi": "'आपने इनाम जीता' वाले मैसेज झूठे होते हैं। क्लिक या फॉरवर्ड न करें।",
            "mr": "'तुम्ही बक्षीस जिंकला' मेसेज खोटे असतात. क्लिक किंवा फॉरवर्ड करू नका.",
            "gu": "'તમે ઇનામ જીત્યા' મેસેજ ખોટા હોય છે. ક્લિક કે ફોરવર્ડ ન કરો.",
        },
        "steps": [
            {"text": {"en": "'You won ₹25,000' messages are always fake.",
                       "hi": "'आपने ₹25,000 जीते' वाले मैसेज हमेशा झूठे होते हैं।",
                       "mr": "'तुम्ही ₹25,000 जिंकला' मेसेज हे खोटे असतात.",
                       "gu": "'તમે ₹25,000 જીત્યા' મેસેજ હંમેશાં ખોટા હોય છે."}},
            {"text": {"en": "Never click unknown links in groups.",
                       "hi": "ग्रुप में अनजान लिंक पर कभी क्लिक न करें।",
                       "mr": "ग्रुपमधील अनोळखी लिंकवर क्लिक करू नका.",
                       "gu": "ગ્રુપમાં અજાણી લિંક પર ક્લિક કરશો નહીં."}},
            {"text": {"en": "Ask the real company on their official app or shop.",
                       "hi": "असली कंपनी से उसकी ऐप या दुकान पर पूछें।",
                       "mr": "खऱ्या कंपनीला तिच्या ॲपवर किंवा दुकानात विचारा.",
                       "gu": "સાચી કંપનીને તેની એપ કે દુકાને પૂછો."}},
        ],
        "quiz": {
            "question": {
                "en": "WhatsApp says you won a prize, with a link. What do you do?",
                "hi": "WhatsApp पर इनाम वाला लिंक आए तो क्या करें?",
                "mr": "WhatsApp वर बक्षीसासह लिंक आला तर काय करावे?",
                "gu": "WhatsApp પર ઇનામ સાથે લિંક આવે તો શું કરવું?",
            },
            "options": [
                {"en": "Click the link fast", "hi": "झटपट लिंक दबाएँ", "mr": "झटपट लिंक दाबा", "gu": "ઝટથી લિંક દબાવું"},
                {"en": "Do not click, it is a scam", "hi": "क्लिक न करें, यह ठगी है", "mr": "क्लिक करू नका, ही फसवणूक आहे", "gu": "ક્લિક ન કરવું, આ છેતરરૂપિયું છે"},
                {"en": "Forward to 10 friends", "hi": "10 दोस्तों को भेजें", "mr": "10 मित्रांना पाठवा", "gu": "10 મિત્રોને મોકલવું"},
            ],
            "correct_index": 1,
        },
    },
    {
        "order": 4,
        "icon": "lock",
        "category": "password",
        "minutes": 2,
        "title": {
            "en": "Strong Password in 1 Minute",
            "hi": "1 मिनट में मज़बूत पासवर्ड",
            "mr": "1 मिनिटात मजबूत पासवर्ड",
            "gu": "1 મિનિટમાં મજબૂત પાસવર્ડ",
        },
        "summary": {
            "en": "Easy passwords are easy to steal. Make a strong one today.",
            "hi": "आसान पासवर्ड चुराना आसान है। आज ही मज़बूत बनाएँ।",
            "mr": "सोपा पासवर्ड चोरणे सोपे असते. आजच मजबूत बनवा.",
            "gu": "સહેલો પાસવર્ડ ચોરવો સહેલો છે. આજે જ મજબૂત બનાવો.",
        },
        "steps": [
            {"text": {"en": "Join 3 easy words, like 'Mango-Train-Sun'.",
                       "hi": "3 आसान शब्द जोड़ें, जैसे 'Aam-Rail-Suraj'.",
                       "mr": "3 सोपे शब्द जोडा, जसे 'Mango-Train-Sun'.",
                       "gu": "3 સહેલા શબ્દ જોડો, જેમ કે 'Mango-Train-Sun'."}},
            {"text": {"en": "Never use your name or birth date.",
                       "hi": "अपना नाम या जन्मतिथि कभी न डालें।",
                       "mr": "तुमचे नाव किंवा जन्मदिनांक वापरू नका.",
                       "gu": "તમારું નામ કે જન્મતારીખ ક્યારેય નહીં."}},
            {"text": {"en": "Keep a different password for the bank app.",
                       "hi": "बैंक ऐप का अलग पासवर्ड रखें।",
                       "mr": "बँक ॲपसाठी वेगळा पासवर्ड ठेवा.",
                       "gu": "બેંક એપ માટે અલગ પાસવર્ડ રાખો."}},
        ],
        "quiz": {
            "question": {
                "en": "Which password is the strongest?",
                "hi": "सबसे मज़बूत पासवर्ड कौन है?",
                "mr": "सर्वात मजबूत पासवर्ड कोणता?",
                "gu": "સૌથી મજબૂત પાસવર્ડ કયો?",
            },
            "options": [
                {"en": "123456", "hi": "123456", "mr": "123456", "gu": "123456"},
                {"en": "ramesh1990", "hi": "ramesh1990", "mr": "ramesh1990", "gu": "ramesh1990"},
                {"en": "Mango-Train-Sun77", "hi": "Aam-Rail-Suraj77", "mr": "Mango-Train-Sun77", "gu": "Mango-Train-Sun77"},
            ],
            "correct_index": 2,
        },
    },
    {
        "order": 5,
        "icon": "account-group",
        "category": "social",
        "minutes": 3,
        "title": {
            "en": "Strangers on Social Media",
            "hi": "सोशल मीडिया के अनजान लोग",
            "mr": "सोशल मीडियावरील अनोळखी मंडळी",
            "gu": "સોશિયલ મીડિયા પર અજાણ્યા લોકો",
        },
        "summary": {
            "en": "Fake profiles befriend you to cheat. Think before you trust.",
            "hi": "फर्जी अकाउंट दोस्ती करके ठगते हैं। भरोसा करने से पहले सोचें।",
            "mr": "खोटी अकाउंट मैत्री करून फसवतात. विश्वास ठेवण्यापूर्वी विचार करा.",
            "gu": "ખોટા એકાઉન્ટ મિત્રતા કરીને છેતરે છે. વિશ્વાસ કરતા પહેલા વિચારો.",
        },
        "steps": [
            {"text": {"en": "Fake profiles use hero photos and sweet talk.",
                       "hi": "फर्जी अकाउंट बड़ी फोटो और मीठी बातें करते हैं।",
                       "mr": "खोटे अकाउंट मोठ्या फोटो आणि गोड बोलणे वापरतात.",
                       "gu": "ખોટા એકાઉન્ટ મોટા ફોટા અને મીઠી વાતો વાપરે છે."}},
            {"text": {"en": "Never send money to online friends.",
                       "hi": "ऑनलाइन दोस्तों को पैसे कभी न भेजें।",
                       "mr": "ऑनलाइन मित्रांना पैसे पाठवू नका.",
                       "gu": "ઓનલાઇન મિત્રોને પૈસા ક્યારેય ન મોકલો."}},
            {"text": {"en": "Do not share personal photos or Aadhaar.",
                       "hi": "निजी फोटो या आधार कभी न भेजें।",
                       "mr": "खाजगी फोटो किंवा आधार पाठवू नका.",
                       "gu": "ખાનગી ફોટા કે આધાર મોકલશો નહીં."}},
        ],
        "quiz": {
            "question": {
                "en": "An online friend asks money for an emergency. What do you do?",
                "hi": "ऑनलाइन दोस्त इमरजेंसी के लिए पैसे माँगे तो क्या करें?",
                "mr": "ऑनलाइन मित्र आपत्तीसाठी पैसे मागितले तर काय करावे?",
                "gu": "ઓનલાઇન મિત્ર ઇમરજન્સી માટે પૈસા માંગે તો શું કરવું?",
            },
            "options": [
                {"en": "Send money fast", "hi": "झटपट पैसे भेजें", "mr": "झटपट पैसे पाठवा", "gu": "ઝટથી પૈસા મોકલો"},
                {"en": "Verify by call or video; do not send", "hi": "कॉल या वीडियो से पुष्टि करें; पैसे न भेजें", "mr": "कॉल किंवा व्हिडिओमध्ये खात्री करा; पैसे पाठवू नका", "gu": "કૉલ કે વિડિયોથી ખાતરી કરો; પૈસા ન મોકલો"},
                {"en": "Ask another friend to send", "hi": "दूसरे दोस्त से भिजवाएँ", "mr": "दुसऱ्या मित्राकडून पाठवा", "gu": "બીજા મિત્ર પાસે મોકલાવો"},
            ],
            "correct_index": 1,
        },
    },
    {
        "order": 6,
        "icon": "briefcase",
        "category": "job",
        "minutes": 2,
        "title": {
            "en": "'Earn Big From Home'? Scam!",
            "hi": "'घर बैठे कमाओ'? ठगी है!",
            "mr": "'घरी बसून कमवा'? फसवणूक!",
            "gu": "'ઘરે બેસી કમાઓ'? છેતરરૂપિયું!",
        },
        "summary": {
            "en": "Real jobs never take money first. 'Easy work, big pay' is a trap.",
            "hi": "असली नौकरी कभी पैसे पहले नहीं माँगती। 'आसान काम, बड़ी कमाई' जाल है।",
            "mr": "खऱी नोकरी आधी पैसे मागत नाही. 'सोपे काम, मोठी कमाई' हा सापळा आहे.",
            "gu": "સાચી નોકરી ક્યારેય પહેલા પૈસા ન માંગે. 'સહેલું કામ, મોટી કમાણી' એ જાળ છે.",
        },
        "steps": [
            {"text": {"en": "'Like videos, earn ₹5,000 daily' is always a scam.",
                       "hi": "'वीडियो देखो, रोज़ ₹5,000 कमाओ' ठगी है।",
                       "mr": "'व्हिडिओ पहा, रोजी ₹5,000 कमवा' ही फसवणूक आहे.",
                       "gu": "'વિડિયો જુઓ, રોજ ₹5,000 કમાઓ' એ છેતરરૂપિયું છે."}},
            {"text": {"en": "Never pay registration or task fees.",
                       "hi": "रजिस्ट्रेशन या काम के पैसे कभी न दें।",
                       "mr": "नोंदणी किंवा कामाचे पैसे कधीही देऊ नका.",
                       "gu": "રજીસ્ટ્રેશન કે કામના પૈસા ક્યારેય ન આપો."}},
            {"text": {"en": "Search the company name on Google with the word 'scam'.",
                       "hi": "कंपनी का नाम Google पर 'scam' शब्द से खोजें।",
                       "mr": "कंपनीचे नाव Google वर 'scam' शब्दासह शोधा.",
                       "gu": "કંપનીનું નામ Google પર 'scam' શબ્દ સાથે શોધો."}},
        ],
        "quiz": {
            "question": {
                "en": "A Telegram job says: pay ₹500, earn ₹5,000 daily. Real?",
                "hi": "टेलीग्राम नौकरी: ₹500 दो, रोज़ ₹5,000 कमाओ। सच है?",
                "mr": "टेलिग्राम नोकरी: ₹500 दा, रोजी ₹5,000 कमवा. खरे आहे का?",
                "gu": "ટેલિગ્રામ નોકરી: ₹500 આપો, રોજ ₹5,000 કમાઓ. સાચું?",
            },
            "options": [
                {"en": "Pay and try", "hi": "पैसे देकर आज़माएँ", "mr": "पैसे देऊन प्रयत्न करा", "gu": "પૈસા આપી પ્રયત્ન કરો"},
                {"en": "It is a scam. Do not pay", "hi": "यह ठगी है। पैसे न दें", "mr": "ही फसवणूक आहे. पैसे देऊ नका", "gu": "આ છેતરરૂપિયું છે. પૈસા ન આપો"},
                {"en": "Borrow money and pay", "hi": "उधार लेकर पैसे दें", "mr": "उसने घेऊन पैसे द्या", "gu": "ઉધાર લઈને પૈસા આપો"},
            ],
            "correct_index": 1,
        },
    },
]

SEED_ALERTS = [
    {
        "severity": "high",
        "published_at": datetime(2026, 6, 20, 10, 0, tzinfo=timezone.utc),
        "title": {
            "en": "New 'Digital Arrest' video call scam",
            "hi": "नया 'डिजिटल अरेस्ट' वीडियो कॉल घोटाला",
            "mr": "नवी 'डिजिटल ॲरेस्ट' व्हिडिओ कॉल युक्ती",
            "gu": "નવી 'ડિજિટલ અરેસ્ટ' વિડિયો કૉલ યુક્તિ",
        },
        "description": {
            "en": "Fraudsters pose as CBI or police on video calls, scare you and demand money. No government agency arrests people on video calls.",
            "hi": "ठग वीडियो कॉल पर CBI या पुलिस बनकर डराकर पैसे माँगते हैं। कोई सरकारी एजेंसी वीडियो कॉल पर गिरफ्तारी नहीं करती।",
            "mr": "फसवणूक करणारे व्हिडिओ कॉलवर CBI किंवा पोलीस बनून घाबरून पैसे मागतात. कोणतीही सरकारी संस्था व्हिडिओ कॉलवर अटक करत नाही.",
            "gu": "છેતરરૂપિયા વિડિયો કૉલ પર CBI કે પોલીસ બનીને ડરાવીને પૈસા માંગે છે. કોઈ સરકારી એજન્સી વિડિયો કૉલ પર ધરપકડ કરતી નથી.",
        },
    },
    {
        "severity": "high",
        "published_at": datetime(2026, 6, 18, 10, 0, tzinfo=timezone.utc),
        "title": {
            "en": "Fake customer care numbers on Google",
            "hi": "Google पर फर्जी कस्टमर केयर नंबर",
            "mr": "Google वर खोटे कस्टमर केअर नंबर",
            "gu": "Google પર ખોટા કસ્ટમર કેર નંબર",
        },
        "description": {
            "en": "Searching a company's phone number shows fake numbers first. Fraudsters ask you to download screen-share apps and steal money.",
            "hi": "कंपनी का नंबर खोजने पर फर्जी नंबर सबसे ऊपर आते हैं। ठग स्क्रीन-शेयर ऐप डलवाकर पैसे चुरा लेते हैं।",
            "mr": "कंपनीचा नंबर शोधताना खोटे नंबर सर्वात वर दिसतात. फसवणूक करणारे स्क्रीन-शेअर ॲप बसवून पैसे चोरतात.",
            "gu": "કંપનીનો નંબર શોધતાં ખોટા નંબર સૌથી ઉપર દેખાય છે. છેતરરૂપિયા સ્ક્રીન-શેર એપ કરાવીને પૈસા ચોરી લે છે.",
        },
    },
    {
        "severity": "medium",
        "published_at": datetime(2026, 6, 12, 10, 0, tzinfo=timezone.utc),
        "title": {
            "en": "'Parcel stuck' OTP scam",
            "hi": "'पार्सल रुका है' OTP ठगी",
            "mr": "'पार्सल अडला आहे' OTP फसवणूक",
            "gu": "'પાર્સલ અટવ્યું છે' OTP છેતરરૂપિયું",
        },
        "description": {
            "en": "Fake courier calls say a parcel with your name is stuck. They ask OTP to 'verify address'. Never share it.",
            "hi": "नकली कूरियर कहते हैं आपका पार्सल रुका है। वे पता 'जाँचने' के लिए OTP माँगते हैं। OTP कभी न बताएँ।",
            "mr": "खोटे कुरियर तुमचा पार्सल अडला असे सांगतात. पत्ता 'तपासण्यासाठी' OTP मागतात. OTP कधीही सांगू नका.",
            "gu": "ખોટા કુરિયર કહે છે તમારું પાર્સલ અટવ્યું છે. સરનામું 'ચકાસવા' OTP માંગે છે. OTP ક્યારેય ન આપો.",
        },
    },
    {
        "severity": "medium",
        "published_at": datetime(2026, 6, 5, 10, 0, tzinfo=timezone.utc),
        "title": {
            "en": "New WhatsApp number of your 'boss'",
            "hi": "आपके 'बॉस' का नया WhatsApp नंबर",
            "mr": "तुमच्या 'बॉस'चा नवीन WhatsApp नंबर",
            "gu": "તમારા 'બોસ'નો નવો WhatsApp નંબર",
        },
        "description": {
            "en": "A new number with your boss's or relative's photo asks for money urgently. Always verify with a call first.",
            "hi": "बॉस या रिश्तेदार की फोटो वाला नया नंबर जल्दी पैसे माँगता है। पहले कॉल करके पुष्टि ज़रूर करें।",
            "mr": "बॉस किंवा नातेवाईकाच्या फोटोसह नवीन नंबर लगेच पैसे मागतो. आधी कॉल करून खात्री करा.",
            "gu": "બોસ કે સગાઈની ફોટાવાળો નવો નંબર તરત પૈસા માંગે છે. પહેલા કૉલ કરીને ખાતરી કરો.",
        },
    },
    {
        "severity": "low",
        "published_at": datetime(2026, 5, 28, 10, 0, tzinfo=timezone.utc),
        "title": {
            "en": "Fake loan apps on the rise",
            "hi": "फर्जी लोन ऐप बढ़ रहे हैं",
            "mr": "खोटे लोन ॲप वाढत आहेत",
            "gu": "ખોટા લોન એપ વધી રહ્યા છે",
        },
        "description": {
            "en": "Loan apps that demand access to contacts threaten and cheat people. Take loans only from banks.",
            "hi": "कॉन्टैक्ट की अनुमति माँगने वाले लोन ऐप धमकी देकर ठगते हैं। लोन सिर्फ बैंक से लें।",
            "mr": "संपर्कांची परवानगी मागणारे लोन ॲप धाक दाखवून फसवतात. कर्ज फक्त बँकेकडून घ्या.",
            "gu": "કોન્ટેક્ટની પરમિશન માંગતા લોન એપ ધમકી આપીને છેતરે છે. લોન ફક્ત બેંકમાંથી લો.",
        },
    },
]

SEED_HELPLINES = [
    {
        "order": 1,
        "type": "phone",
        "number": "1930",
        "url": None,
        "name": {
            "en": "Cyber Crime Helpline",
            "hi": "साइबर क्राइम हेल्पलाइन",
            "mr": "सायबर क्राइम हेल्पलाइन",
            "gu": "સાયબર ક્રાઇમ હેલ્પલાઇન",
        },
        "description": {
            "en": "Report online fraud fast — money can be stopped",
            "hi": "ऑनलाइन ठगी की खबर तुरंत दें, पैसे रुक सकते हैं",
            "mr": "ऑनलाइन फसवणूक लगेच कळवा, पैसे थांबवता येतात",
            "gu": "ઓનલાઇન છેતરરૂપિયું તરત જણાવો, પૈસા અટકાવી શકાય",
        },
    },
    {
        "order": 2,
        "type": "phone",
        "number": "112",
        "url": None,
        "name": {
            "en": "National Emergency",
            "hi": "राष्ट्रीय आपातकाल",
            "mr": "राष्ट्रीय आपत्कालीन",
            "gu": "રાષ્ટ્રીય કટોકટી",
        },
        "description": {
            "en": "Police, fire and ambulance — one number",
            "hi": "पुलिस, फायर और एम्बुलेंस — एक ही नंबर",
            "mr": "पोलीस, अग्निशमन आणि रुग्णवाहिका — एकच नंबर",
            "gu": "પોલીસ, ફાયર અને એમ્બ્યુલન્સ — એક જ નંબર",
        },
    },
    {
        "order": 3,
        "type": "phone",
        "number": "181",
        "url": None,
        "name": {
            "en": "Women Helpline",
            "hi": "महिला हेल्पलाइन",
            "mr": "महिला हेल्पलाइन",
            "gu": "મહિલા હેલ્પલાઇન",
        },
        "description": {
            "en": "Help for women facing harassment or fraud",
            "hi": "छेड़छाड़ या ठगी का शिकार महिलाओं की मदद",
            "mr": "छेडछाड किंवा फसवणूकीतील महिलांसाठी मदत",
            "gu": "ઉત્પીડન કે છેતરરૂપિયામાં મહિલાઓની મદદ",
        },
    },
    {
        "order": 4,
        "type": "phone",
        "number": "1098",
        "url": None,
        "name": {
            "en": "Child Helpline",
            "hi": "चाइल्ड हेल्पलाइन",
            "mr": "बाल हेल्पलाइन",
            "gu": "ચાઇલ્ડ હેલ્પલાઇન",
        },
        "description": {
            "en": "Help for children in danger, including online",
            "hi": "खतरे में बच्चों की मदद — ऑनलाइन भी",
            "mr": "धोक्यातील मुलांसाठी मदत — ऑनलाइनही",
            "gu": "જોખમમાં બાળકોની મદદ — ઓનલાઇન પણ",
        },
    },
    {
        "order": 5,
        "type": "web",
        "number": None,
        "url": "https://cybercrime.gov.in",
        "name": {
            "en": "Cyber Crime Portal (Online)",
            "hi": "साइबर क्राइम पोर्टल (ऑनलाइन)",
            "mr": "सायबर क्राइम पोर्टल (ऑनलाइन)",
            "gu": "સાયબર ક્રાઇમ પોર્ટલ (ઓનલાઇન)",
        },
        "description": {
            "en": "File a complaint on the official website",
            "hi": "सरकारी वेबसाइट पर शिकायत दर्ज करें",
            "mr": "सरकारी संकेतस्थळावर तक्राद नोंदवा",
            "gu": "સરકારી વેબસાઇટ પર ફરિયાદ નોંધાવો",
        },
    },
]
